### ISSUE TITLE
Duplication problem for generated sources

### ISSUE THREAD

**Issue by NiccoMlt** [kaby76/Antlr4BuildTasks#3] opened 2020-04-26 20:05 UTC
I tried integrating Antlr4BuildTasks in a C# project to auto-generate lexer and parser from an ANLTR grammar but I'm having some problems: the project seems to compile and run correctly, but the IDEs report many errors related to the generated code.

The error can be replicated generating a new project with the template from this repo.
Scaffolding a new project with the template, lines 12 (`var lexer = new arithmeticLexer(str);`) and 14 (`var parser = new arithmeticParser(tokens);`) of the `Program.cs` file reports "Ambiguous constructor reference" and inspecting the generated source code it is possible to find many error like "Duplicated attribute [...]" of "Member with the same name is already declared".
However, code still compiles and run fine using `dotnet` from command line.

I'm pretty new with C# and the .NET world, so maybe I'm missing something stupid, but I can't explain this behavior.

For reference, I'm experiencing the problem described above both on Manjaro Linux 19.0.2 with .NET Core 3.1.103 on JetBrains Rider 2020.1.0 and on Windows 10 1909 with .NET Core 3.1.201 and both JetBrains Rider 2020.1.0 an Visual Studio Enterprise 2019.

**Comment by kaby76** [comment] 2020-04-27 15:18
I can reproduce this in JetBrains Rider, but it does not make any sense.

First, I generate, build, and run the Antlr program from the template: "mkdir test_antlr; cd !$; dotnet new antlr; dotnet restore; dotnet build; dotnet run".  If I then open Rider on "test_antlr.csproj", it now underscores the "str" variable on line 11 "var lexer = new arithmeticLexer(str);". Clicking on "str" in the constructor call, the hover pop-up says "Ambiguous constructor reference", followed by two definitions for the constructor, which would explain why it says it's ambiguous. But, where are these two defining occurrences it thinks?? If I try use Rider "Find" of "arithmeticLexer", Rider finds only the applied occurrence in Program.cs, on line 11. "Next Occurrence (F3)" does not find the occurrences in obj/Debug/netcoreapp3.1/arithmeticLexer.cs, exactly where the build rules I wrote on where to put the damn generated C# files from the Antlr .g4 grammar file. I do a grep for "arithmeticLexer" in the entire sub-directory test_antlr/, and it says it's in the generated file. The fact that Find does not work like any editor I've used since the 1970s is reason to not use this piece of junk!

I would recommend you use Visual Studio 2019 or Visual Studio Code or even just Emacs or vi. You shouldn't have to put up with this garbage. It is likely the parser used by Rider to analyze C# code is junk.

--Ken

**Comment by NiccoMlt** [comment] 2020-04-27 16:11
Thanks for your answer!

I agree with you that this error makes no sense: I couldn't find the duplicated occurence either.
The problem is, that as I said I also tried with Visual Studio Enterprise 2019 and I'm getting the same exact error!

I have not tried with VS Code yet; I will try with it and report you back.

**Comment by kaby76** [comment] 2020-04-27 16:34
On a hunch, I decided to copy the Antlr generated files to the same directory as where the rest of the C# source files reside, removed the Antlr4BuildTasks requirement and <Antlr4> element from the .csproj, and test with a build/run. If I now open Rider on the project, I now see that it doesn't report any errors. So, it has to do with files that are generated and placed in obj/. I've read that Rider uses Roslyn from Net Core, so it should just work--if Roslyn works. The fact that you see VS2019 reporting the same error is interesting because everything uses Roslyn. It's worth investigating this further because I already use Roslyn for C# parsing in an Antlr plugin (e.g., to find out what is a start symbol in the grammar by looking at the C# code, because the grammar doesn't have declarations for start symbols).

**Comment by NiccoMlt** [comment] 2020-04-27 18:39
I tried with Visual Studio Code with the C# extension (which uses OmniSharp under the hood) and it seems not to complain like the other IDEs do. It's weird that this works correctly while VS2019 and Rider don't, because as far as I know OmniSharp uses Roslyn too.

**Comment by NiccoMlt** [comment] 2020-05-02 13:24
Hi, I'm sorry for bothering you again.
Even if I presume you deprecated it, I tried importing the example project currently linked in the README of this repo ([this one](https://github.com/kaby76/AntlrHW), which is flagged as archived on GitHub and uses Antlr4BuildTasks version 1.0.7).
After playing with it a little, I discovered that all the versions 1.x don't give any error in any IDE.
Upgrading to version 2 or above, the problem we discussed previously occurs.

I couldn't find any changelog in this repo, so maybe you could tell me better than what I can understand inspecting Git commits: what changed after version 1.10.0? What could possibly confuse the IDEs in newer versions?

**Comment by kaby76** [comment] 2020-05-02 15:04
That's interesting. I haven't figured this out yet, and was looking at Roslyn as a possible avenue, but ran into a bug there. Will check this out. For whatever reason, it thinks the file is being included twice, so it reports symbols being defined again.

**Comment by NiccoMlt** [comment] 2020-06-08 12:40
Hi, you released many new versions as I can see.
I tried them in a dummy project but the problem seems not to be fixed yet.

Will you address this issue in the near future?
I'm asking because I need a solution to build parsers from ANTLR grammars in a C# project I'm starting right now for my work.
I really like the ease with which this project allows you to integrate an ANTLR-generated parser into a C# solution using the latest version of the runtime (not the custom C#-optimized one), but if you think this iusse still requires a lot of work to be fixed, I will probably choose another solution.

**Comment by kaby76** [comment] 2020-06-08 13:25
I haven't looked at this "dup error" problem much yet. The changes I did were to get the tool to run on Linux because the build tool was trying to fork "$JAVA_HOME/bin/java.exe" on Linux. So, JAVA_HOME has been replaced with JAVA_EXEC (the full path of the Java excutable). I have some ideas of what could be wrong with the build rules with Rider.

**Comment by NiccoMlt** [comment] 2020-06-08 13:44
> The changes I did were to get the tool to run on Linux because the build tool was trying to fork "$JAVA_HOME/bin/java.exe" on Linux. 

What a strange error, I used your tool on both Manjaro Linux and Windows 10 without any issue (apart from this "dup error" problem, of course).
Also, usually referencing `$JAVA_HOME/bin/java` is enough on both Windows and Linux; as a mainly JVM developer, I find the usage `JAVA_EXEC` instead of `JAVA_HOME` a bit "weird", but if it is the only way you figured out, I respect that :smiley:.

> I haven't looked at this "dup error" problem much yet.

> I have some ideas of what could be wrong with the build rules with Rider.

That's OK, take your time, and thanks for your work.

I'm probably too new to the dotnet build system to be of any help, but if think there is anything I can do to help, feel free to ask.

**Comment by kaby76** [comment] 2020-06-08 14:10
I believe the issue is with the build rules in Antlr4BuildTasks.target--there seems to be a duplication of adding the source files to a list of dependencies. That's why you get these dup/ambiguous constructor errors. Further, when I try to use different directories for build and intermediate output, it can't even find the tool-generated files. These rules are still way too complicated (I forked this code from the Antlr guys, they haven't maintained this for many years, and this can be much cleaner), so I will need to make some changes to the build files. Otherwise, the build looks okay if you don't change output directories. --Ken

**Comment by kaby76** [comment] 2020-06-08 17:32
* Errors flagging duplicates (yet with a clean build) seems to be a problem that is being reported often with Rider. https://rider-support.jetbrains.com/hc/en-us/community/posts/360006744760-Duplicate-attribute-errors-seem-unreasonable .
* I updated to 2020.1.3, invalidated, and cleared the caches, and _it still occurs._
* I removed the .idea subdirectory, and restarted. _It still fails._
* "Go to def" navigates to the lexer and parser classes for the grammar, but the editor flags dup errors for all methods and fields of the generated .cs file.
* I removed the generated .cs file names from the obj/Debug/netcoreapp3.1/xpath.csproj.FileListAbsolute.txt because that's where the files are explicitly listed for the <BuildDependsOn> .cs file additions to compile. _I still see the problem. Strange. It should not know at all of these files. any of this code, but it still thinks there are two definitions for the lexer and parser! Could it be something about having the generated files in obj/?_
* Commented out the &lt;PackageReference Include="Antlr4BuildTasks" Version="6.1" /&gt; in the .csproj file. Rider should now has no idea where or what those generated files are in /obj. _It now flags the lexer and parser references in the main program as undefined. OK, it needs the package to determine the dependencies._
* Made a copy of the obj/ directory and placed in on another drive, and then in the obj/ directory, changed the ...FileListAbsolute.txt file the new path of the files. Get UNDEFINED references to the lexer and parser classes. AH HA!! Rider does not seem to process <BuildDependsOn> in the build rules. That's bogus!
* I copy the obj/ with the generated .cs files to sav/ and remove all the generated .cs files in obj/. _It works---no errors. AH HA! Rider reads the subdirectories but has some special logic for obj/._

One solution is to generate the .cs files to another directory other than obj/... But, Antlr4BuildTasks does not have an option to set this. I'll make the change sometime today. It should be a workaround for you.

--Ken

**Comment by NiccoMlt** [comment] 2020-06-08 22:29
Great!
Thank you very much for your investigations!

**Comment by kaby76** [comment] 2020-06-08 23:31
It's getting there. The "dup error" bug in Rider now is fixed. Looks like Rider doesn't like generated files in obj/, so you can set the output directory to $(ProjectDir). I just might make that the default because you kind of like to open the generated file to set a breakpoint without doing an "open => obj/Debug/netcoreapp3.1/.... But, the cleaning up of the generated files is broken, so I need another day to fix. Sorry.

**Comment by NiccoMlt** [comment] 2020-06-09 08:09
Don't worry, it's great to hear that the cause behind the bug is clear now!
Take the time you need.

**Comment by kaby76** [comment] 2020-06-09 16:39
Fixed in 7.0.

**Closed by kaby76** 2020-06-09 16:39 UTC

**Comment by kaby76** [comment] 2020-06-09 18:19
@NiccoMlt -- make sure you pick up the latest version 7.1 not 7.0 if you use "import" in a .g4 file. This is because whoever wrote the Antlr Tool -depend option didn't know what they are doing. .g4's do not depend on .g4's. Only generated files depend on all inputs. So in version 7.0, the tool removes one of the .g4's!!!

**Comment by NiccoMlt** [comment] 2020-06-09 18:39
Ok, thanks
